### ISSUE TITLE
Nidaqmx Problem Read and Depreciation

### ISSUE THREAD

**Issue by syl49** [ni/nidaqmx-python#119] opened 2021-03-15 10:06 UTC
Hello Teams, 
Our teams have two problems.
We use nidaqmx python library 0.57 for control a NI6501
Python version 3.8
Numpy version 1.20.1

Problem 1 :
```python
with nidaqmx.Task() as task:
      task.di_channels.add_di_chan(dev_str, line_grouping = LineGrouping.CHAN_PER_LINE)
```

When you make a read, the following error appears
```
    rtn = task.read()
  File "C:\Python3\lib\site-packages\nidaqmx\task.py", line 635, in read
    data = numpy.zeros(array_shape, dtype=numpy.bool)
  File "C:\Python3\lib\site-packages\numpy\__init__.py", line 287, in __getattr_
_
    warnings.warn(msg, DeprecationWarning, stacklevel=2)
DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To s
ilence this warning, use `bool` by itself. Doing this will not modify any behavi
or and is safe. If you specifically wanted the numpy scalar type, use `np.bool_`
 here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdo
cs/release/1.20.0-notes.html#deprecations
```

Problem 2 :
the second problem is when we are in output digital channels
and you make a read, only for Dev1/port0/line0:3 works, the others line doesn't works,
try with port 1, all line read doesn't works (ex Dev1/port1/line0:7)

A example below, here the `print(f"do_read : {do_read}");` indicate 15, that means 
only Dev1/port0/line0:3 has modified and physically the line 4 et 5 are not to True on the board NI6501

If you remove the line `do_read = task.read(number_of_samples_per_channel=1)` from the code
all lines are well modified to True  physically on the board
We are not sure but it's seems that when you make a read for line higher Dev1/port0/line3 (ex 
Dev1/port0/line5), the channels changed into di_channels instead to stay to  do_channels
```python
################################################
import nidaqmx
from nidaqmx.constants import LineGrouping

dev_str = "Dev1/port0/line0:5"

with nidaqmx.Task() as task:
	task.do_channels.add_do_chan(dev_str, line_grouping=LineGrouping.CHAN_FOR_ALL_LINES)
	
	for chnl in task.do_channels:
		chnl.do_output_drive_type = nidaqmx.constants.DigitalDriveType.OPEN_COLLECTOR
		print(f"Drive type après : {chnl.do_output_drive_type}");
	
	task.start()
	
	task.write(15+32+16)
	print(f"do_write ");
	# print(f"do_is : {do_is}");
	do_read = task.read(number_of_samples_per_channel=1)
	print(f"do_read : {do_read}");
################################################
```

**Comment by zhindes** [comment] 2022-02-08 21:53
The first issue was resolved in the latest few releases.

The second issue I was not able to reproduce. Ensure you aren't driving those lines with a signal causing the readback to fail perhaps?

```
C:\Users\Administrator\nidaqmx-python>poetry run python test.py
6
do_write
do_read : [63]
```

**Closed by zhindes** 2022-02-08 21:53 UTC
